// here lies scripts for CScript class
// testlevel.script is an example of script syntax
//
// this file is executed by comman CScript::Load()
//
// this block applies immidiately after loading,
// others are being stored

[MAIN]
goto camera 9 432
blackout
startcamerafollow
showbuttons
startcontrol
#

[RESTART]
loadlevel levels/lev1-4.lev
#

[NEXTLEVEL]
blackin
timer 2 NEXTLEVEL_2
#

[NEXTLEVEL_2]
loadlevel levels/lev1-5.lev
#

//stupid

